name: rest_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.2.0
  build_runner: ^2.4.9
  injectable: ^2.4.4
  injectable_generator: ^2.6.2

  core:
    path: ../../core
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  retrofit_generator: ^8.2.0
  
  json_annotation: ^4.9.0
  very_good_analysis: ^5.1.0
